### PR TITLE
Add more linting, and fix errors found by linters

### LINKED ISSUE #12: Add linting, and fix errors
This will allow shrinking scope of #2 to just call whatever gets added for this issue.

* Ruff (format and errors)
* Clippy (fix any errors)
* cargo fmt (fix any errors)

### PR DESCRIPTION
**Pull request by itamarst**
Fixes #12 

Not sure what's up with the two unused functions; should they just be deleted?

Next will be GitHub Actions so that this doesn't degrade.

### CODE REVIEW

File: python/src/lib.rs [hunk 1]
```diff
@@ -36,27 +47,21 @@ fn compact(
...
-#[pyo3(signature = (table_uri, sort_columns, nulls=None))]
-fn validate(
-    py: Python<'_>,
+#[pyo3(signature = (table_uri, sort_columns, nulls="first"))]
+fn validate<'py>(
+    py: Python<'py>,
     table_uri: String,
     sort_columns: Vec<String>,
-    nulls: Option<String>,
-) -> PyResult<Bound<PyDict>> {
```
Comment (tolleybot) [inline python/src/lib.rs:55]: No action needed.  Just curions if Option<String> was just a version issue?

**Review by tolleybot — APPROVED** [review]
